version: "3.8"
services:
  master:
    build:
      context: ./master
    container_name: gridmr_master
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    environment:
      # Lista interna de workers en la red compose (servicio:port/endpoint)
      - WORKERS=http://worker1:8001,http://worker2:8001,http://worker3:8001
      - WORKER_STATUS_PATH=/status
      - WORKER_PROCESS_PATH=/process_split
      - MAX_RETRIES=3
      - WORKER_REQUEST_TIMEOUT=20

  worker1:
    build:
      context: ./worker
    container_name: gridmr_worker1
    volumes:
      - ./data:/data
    ports:
      - "8101:8001"
    environment:
      - CAPACITY=3

  worker2:
    build:
      context: ./worker
    container_name: gridmr_worker2
    volumes:
      - ./data:/data
    ports:
      - "8102:8001"
    environment:
      - CAPACITY=1

  worker3:
    build:
      context: ./worker
    container_name: gridmr_worker3
    volumes:
      - ./data:/data
    ports:
      - "8103:8001"
    environment:
      - CAPACITY=2
